blank_issues_enabled: false
contact_links:
  - name: General question
    url: https://github.com/novax414/pdfimgq-issues/issues
    about: Use the issue tracker for general questions, bug reports, and feature requests.
